### ISSUE TITLE
Camelcase filenames for consistency

### ISSUE THREAD

**Issue by rreusser** [stackgl/gl-mat3#3]
All of the other stackgl modules use camelCased filenames instead of hyphen-cased filenames. It's a quirk at the moment that you have to remember `gl-mat3` is the one that you require differently. I'll submit a PR to change this and bump the major version unless someone prefers otherwise. (@mattdesl? @hughsk?)

**Comment by mikolalysenko** [comment]
👍

**Comment by rreusser** [comment]
Resolved by #4.
